
service: email-ses-template

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:

resources:
  Resources:
    Template:
      Type: 'AWS::SES::Template'
      Properties:
        Template:
          TemplateName: "${self:service}-Template"
          SubjectPart: 'Voicemail from {{callback_number}}'
          TextPart: 'A voicemail was left for the {{entity_name}} queue from {{callback_number}}. You can listen to the message via the following URL: {{presigned_url}}'
          HtmlPart: ${file(./template.html)}
            