
service: email-ses-template

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:

resources:
  Resources:
    Template:
      Type: 'AWS::SES::Template'
      Properties:
        Template:
          TemplateName: "${self:service}-Template"
          SubjectPart: 'Voicemail from {{callback_number}}'
          TextPart: 'A voicemail was left for the {{entity_name}} queue from {{callback_number}}. You can listen to the message via the following URL: {{presigned_url}}'
          HtmlPart: |
            <!DOCTYPE html
            <html>
              <head>
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <meta charset="utf-8"/>
                  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;800&display=swap" rel="stylesheet">
                  <style type="text/css">
                      * {
                          margin: 0;
                          padding: 0;

                      }
                  </style>
              <body>
               {{name}}
              </body>
            </html>
